### PR TITLE
Fizz Buzz in PowerShell

### LINKED ISSUE #311: Add a Fizz Buzz script for PowerShell
I've already written one but wanted an issue to accompany it and the article I'll write alongside it.

### PR DESCRIPTION
**Pull request by Alcha**
- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [x] I plan to write the article for this code snippet
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README
- [x] I fixed #311

### CODE REVIEW

**Comment by Alcha** [comment]
I'll go ahead and update the README for PowerShell to include references and push the commits. I've got a little party to get to so I'll have to do this later tonight, but at least this is a starting point.

**Comment by Alcha** [comment]
Fuck it, went ahead and spent a moment to update the README as well so this PR should be good to merge whenever you can take a look @jrg94.

**Comment by Alcha** [comment]
Also, just so it's in the same thread, I've created [an issue](#311) for this script so we can close it whenever we merge this pr.

**Comment by jrg94** [comment]
Sounds good! I added the fixed line to the original pull request which should auto-close #311 when this pull request merges.

**Comment by Alcha** [comment]
I made one last change to the variable names so they're more "PowerShell-y", as they prefer variables to start with a capital letter, I updated `$x` to `$X`.

**Comment by jrg94** [comment]
Ran this quickly through [TIO](https://tio.run/#powershell) and everything works great!

**Comment by jrg94** [comment]
I removed the signed commit requirement on this repo, so other collaborators can approve pull requests. That should speed things up, so I don't have to merge everything all the time. 😸

**Comment by jrg94** [comment]
It looks like the wiki automation worked :)

**Pull request merged**
