### PR TITLE
Hello World & Reverse a String in Bash

### PR DESCRIPTION
**Pull request by thisisabdus**
## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [x] I created/updated the language README
  - [x] I added the sample program name to the README
  - [x] I added fun facts (i.e. debut, developer, typing, etc.)
  - [x] I added reference link(s) to the README

### Test cases for reverse string program
- No Input  PASSED
- Empty String PASSED
- Ascii String PASSED
- Accented String PASSED
- Chinese String PASSED
- Emoji String NOT TESTED

### CODE REVIEW

**Comment by jrg94** [comment]
This looks excellent! Thank you.

**Comment by jrg94** [comment]
By the way, it works with emojis as far as I can tell.

**Comment by thisisabdus** [comment]
Thank you @jrg94. I didn't actually tested emoji strings as I had no emoji support in my machine.

**Comment by jrg94** [comment]
Oh, I ran everything in an online bash shell: http://rextester.com/l/bash_online_compiler

Everything worked well there.

**Comment by thisisabdus** [comment]
I will keep this in mind in future testings. :)

**Pull request merged**
