### PR TITLE
Reverse a String in VB.NET

### PR DESCRIPTION
**Pull request by AaronLenoir**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language](https://therenegadecoder.com/code/sample-programs-in-every-language/) repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [X] I named the pull request using `<Sample Program> in <Language>` format
- [X] I created/updated the language README
  - [X] I added the sample program name to the README
  - [X] I added fun facts (i.e. debut, developer, typing, etc.)
  - [X] I added reference link(s) to the README

## Notes

This is an implementation using strings and char arrays. It can be done in one line using Linq and some other ways.

If I were to do it in real life, it would probably not be like this, so I'm not sure if this is the best implementation?

### CODE REVIEW

**Comment by jrg94** [comment]
Looks good! However, I wasn't able to run the code in any of the online editors:

- https://dotnetfiddle.net/#
- https://www.jdoodle.com/compile-vb-dot-net-online

Is the solution missing a reference to System?

**Comment by jrg94** [comment]
Also, as a comment to what you said, I generally prefer the complete solution. Actually, I used a one-liner in Java because it handles things like emojis, so you're free to do that as well.

**Comment by AaronLenoir** [comment]
Thanks, good comments. Interestingly, I was compiling used the visual basic compiler "vbc.exe" and it didn't complain about using Console without first importing the System namespace. But indeed jsFiddle doesn't like it. I now write System.Console... and it's fine.

I hadn't tried the emojis because I couldn't get them pasted in the console. But I can get them in with JSFiddle, however, something funky is happening as soon as I try to get the character at the position of the emoji: JSFiddle **immediatly** returns with an error that the execution time limit was exceeded, on "line -1". So I'm a little confused by that and am looking into that now.

**Comment by jrg94** [comment]
I got a chance to run it, and it works great for everything but the emojis. In fact, I got the same error:

```
[DotNetFiddle.Infrastructure.LimitExceededException: Execution time limit was exceeded]
```

I'll add a note to the README and merge it for now. If you ever figure out the issue, feel free to open another pull request.

Otherwise, it works great! Thanks, again.

**Comment by AaronLenoir** [comment]
I don't know if I'll get the Emoji thing to work. When I don't reverse the Char array, it can correctly return the Emoji string. But if I revers the Chars things break. I'm not very familiar with how Emoji's work, but it looks like they are more than one Unicode char.

To get this to work, I'll have to look a little further.

**Pull request merged**
