### PR TITLE
Hello World in LOLCODE & C*

### PR DESCRIPTION
**Pull request by mraza007**
Hi, I have added The Hello world program in LOLCODE programming please preview the code and let me know if there are any changes needed.
I have also added Hello world in C* language I hope that's right it was hard to find good documentation on this programming language

### CODE REVIEW

**Comment by jrg94** [comment]
Looks good to me. The only gripe I have is with the naming of the folder for C*. Any chance you could change it to `c*`. If not, maybe `c-star`. The first way is preferred, but I'm not sure if that token is allowed.

Also, can you add READMEs to those directories?

**Comment by mraza007** [comment]
I was trying to do it using terminal didn't work let me do it the other way .

**Comment by mraza007** [comment]
Done I have changed the folder name

**Comment by jrg94** [comment]
Nice! Can you add READMEs now?

Example: https://github.com/jrg94/sample-programs/blob/master/archive/c/c/README.md

**Comment by jrg94** [comment]
The link syntax is like this:

`[name](url)`

If you look at the [raw markdown](https://raw.githubusercontent.com/jrg94/sample-programs/master/archive/c/c/README.md), you'll see what I'm talking about. 😃

**Comment by jrg94** [comment]
Just noticed the `c*` folder. Anyway to make that lowercase? Just for consistency.

**Comment by mraza007** [comment]
Sure I will do that that :smile:

**Comment by jrg94** [comment]
What happened to crystal? 😭

**Comment by jrg94** [comment]
Perfect! It all looks great 💃

**Pull request merged**
