### PR TITLE
Reverse a String in Scheme

### PR DESCRIPTION
**Pull request by frpeters**
Congrats on taking the first step to contributing to the [Sample Programs in Every Language](https://therenegadecoder.com/code/sample-programs-in-every-language/) repository!

For simplicity, please make sure that your pull request includes one and only one sample program and language.

## Please Complete the Following

- [ ] I would **NOT** like credit for my contribution in the article (credit will be included otherwise)
- [x] I named the pull request using `<Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut, developer, typing, etc.)
  - [ ] I added reference link(s) to the README

## Notes

added reverse string to Scheme.

### CODE REVIEW

**Comment by jrg94** [comment]
Looks great! I'm not super familiar with Scheme. That said, it looks like you defined the Reverse String function, but I don't see any way to pass a string to it on standard input. In other words, this solution doesn't appear to be executable.

Any chance you can add the ability to pass a string on the command line?

**Comment by frpeters** [comment]
Sure!, my bad, let me fix it.

**Comment by frpeters** [comment]
Now it works as it should, tested! :)

**Comment by jrg94** [comment]
Great! I tested really quick, and it even works with emojis which is awesome. 

Do we need a display command to get the string to print to the user? At least, that's what I had to add just for testing purposes: https://www.jdoodle.com/execute-scheme-online

**Comment by frpeters** [comment]
Just to be sure let's add it, I'm using DrRacket and it's not necesary to use (display) as it echoes every variable you put between (), but it won't hurt, I'll add a display at the end.

**Pull request merged**
